<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bw_dpsg_design"
 *
 * Auto generated by Extension Builder 2017-10-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'DPSG Theme for Typo3',
    'description' => 'Ein Theme für TYPO3 im Corperated Design der Deutschen Pfadfinderschaft Sankt Georg.',
    'category' => 'plugin',
    'author' => 'Yannik Börgener',
    'author_email' => 'kontakt@boergener.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.1.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.22-8.7.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
